default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: postcards_to_voters_party_development

test:
  <<: *default
  database: postcards_to_voters_party_test

production:
  <<: *default
  database: <%= DATABASE_URL %>
