default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: postcards_to_voters_party_development

test:
  <<: *default
  database: postcards_to_voters_party_test

production:
  <<: *default
  database: <%= ENV['POSTCARDS_TO_VOTERS_PARTY'] %>
  username: <%= ENV['POSTCARDS_TO_VOTERS_PARTY_DATABASE_USERNAME'] %>
  password: <%= ENV['POSTCARDS_TO_VOTERS_PARTY_DATABASE_PASSWORD'] %>
